#header
menu:
  ABOUT_US:
    title: ABOUT_US
    link: /
    submenu:
      About_VanLangIPA:
        title: About Van Lang IPA
        link: /2015/11/07/about-us
        class: no-menu
      Out_Leadership:
        title: Our Leadership
        link: /2015/11/07/leadership-team/
        class: no-menu
      Out_Team:
        title: Our Team
        link: /2015/11/07/leadership-team/
        class: no-menu

  FOR PROVIDERS:
    title: FOR PROVIDERS
    link: /
    submenu:
      Claims:
        title: Claims
        link: /
        class: submenu
        submenu:
          How_to_create_a_claim_batch_in_eCW_for_VLIPA:
            title: How to create a claim batch in eCW for VLIPA
            link: /2015/11/07/guide/how-to-create-a-claim-batch-in-ecw-for-vlipa/
          How_to_setup_paper_claim_in_Athena:
            title: How to setup paper claim in Athena
            link: /2015/11/07/guide/how-to-set-up-paper-claims-in-athena/
          Setup_VLIPA_as_a_favourite_in_Athena:
            title: Setup VLIPA as a favourite in Athena
            link: /2015/11/07/guide/set-up-van-lang-ipa-as-a-favorite-in-athena/
          How_to_file_claims:
            title: How to file claims
            link: /2015/11/07/guide/tips-on-how-to-file-claims/
      Prior_Authorization:
        title: Prior Authorization
        link: /
        class: submenu
        submenu:
          RioTab_Access_Introduction:
            title: RioTab Access Introduction
            link: /2015/11/14/prior-authorization/riotap-intro/
          Authorization:
            title: Authorization
            link: /2016/05/11/prior-authorization/authorization/
      Forms:
        title: Forms
        link: /
        class: submenu
        submenu:
          Letter_of_Agreement(LOA):
            title: Letter of Agreeement(LOA)
            link: /2015/11/14/forms/loa/
          Credentialing)_Pratitioner_Rights_Notice:
            title: (Credentialing) Pracititioner RIghts Notice
            link: /2015/11/14/forms/cred-practitioner-rights/
          Credentialing)_Texas_Standard_Credentialing:
            title: (Credentialing) Texas Standard Credentialing
            link: /2015/11/14/forms/cred-tx-credentialing/
          Credentialing)_Business_Associate_Agreement:
            title: (Credentialing) Business Associate Agreement
            link: /2015/11/14/forms/baa/
      HCC_Coding:
        title: HCC Coding
        link: /
        class: submenu
        submenu:
          Risk Adjustment Documentation, Coding & Quality Toolbook:
            title: Risk Adjustment Documentation, Coding & Quality Toolbook
            link: /2015/11/14/hcc/risk-adjustment-toolbox/
          ICD-9-CM Medicare Diagnosis Codes (Senior Patient, PCP):
            title: ICD-9-CM Medicare Diagnosis Codes (Senior Patient, PCP)
            link: /2015/11/14/hcc/senior-patient/
          ICD 10 - Internal Medicine:
            title: ICD 10 - Internal Medicine
            link: /2015/11/14/hcc/icd10-internal-medicine/
          Documenting and Coding Chronic Conditions Presentation (Sep-2015):
            title: Documenting and Coding Chronic Conditions Presentation (Sep-2015)
            link: /2015/11/14/hcc/coding-chronic-conditions/
          General Coding Education:
            title: General Coding Education
            link: /2015/11/14/hcc/general-coding-education/
      HEDIS / RAF:
        title: HEDIS / RAF
        link: /
        class: submenu
        submenu:
          HEDIS Score Timeline:
            title: HEDIS Score Timeline
            link : /2015/11/14/hedis/score-timeline/
      Diabetes Management:
        title: Diabetes Management
        link: /
        class: submenu
        submenu:
          IMPORTANT 2017 Coverage Changes for Diabetic Supplies :
            title: IMPORTANT 2017 Coverage Changes for Diabetic Supplies
            link: /2017/01/05/diabetes-management/Coverage-for-diabetes-supply/
      Med Management:
        title: Med Management
        link: /
        class: submenu
        submenu:
          Amerigroup Drug Alternatives:
            title: Amerigroup Drug Alternatives
            link: /2016/01/25/med-management/amerigroup-drug-alternatives/
      Video:
        title: Video
        link: /
        class: submenu
        submenu:
          Early detection triples a patient's chances of survival from crc:
            title: Early detection triples a patient's chances of survival from crc
            link: /2015/11/07/video/early-detection-triples-a-patients-chances-of-survival-form-crc/
      TIFL Two-Factor Authentication Guide:
        title: TIFL Two-Factor Authentication Guide
        link: /
        class: no-menu
  PAYER BENEFITS:
    title: PAYER BENEFITS
    link : /
    submenu:
      Summary of Benefits for Amerivantage Dual Coordination (HMO SNP):
        title: Summary of Benefits for Amerivantage Dual Coordination (HMO SNP)'
        link: /2017/01/05/payer-benefits/2017-benefits-specialty/
        class: no-menu
      Summary of Benefits for Amerivantage Classic (HMO) and Amerivantage Select (HMO):
        title: Summary of Benefits for Amerivantage Classic (HMO) and Amerivantage Select (HMO)
        link: /2016/01/06/payer-benefits/benefits_classic_and_select_2016/
        class: no-menu
  DRUG FORMULARY:
    title: DRUG FORMULARY
    link: /
    submenu:
      Amerivantage Specialty:
        title: Amerivantage Specialty
        link: /2017/01/05/drug-formulary/2017-amerivantage-specialty-formulary/
        class: no-menu
      Amerivantage Select:
        title: Amerivantage Select
        link: /2017/01/05/drug-formulary/2017-amerivantage-select-formulary/
        class: no-menu
      Amerivantage Classic:
        title: Amerivantage Classic
        link: /2017/01/05/drug-formulary/2017-amerivantage-classic-formulary/
        class: no-menu
      2017 Over-the-Counter Health Products Catalog:
        title: 2017 Over-the-Counter Health Products Catalog
        link: /2017/01/05/drug-formulary/Amerigroup_OTC_Catalog_2017/
        class: no-menu
      Walmart $4 drug list:
        title: Walmart $4 drug list
        link: /2017/04/05/drug-formulary/Walmart_usd4_drug_list/
        class: no-menu
      Medicaid:
        title: Medicaid
        link: /
        class: submenu
        submenu:
          Medicaid Preferred Drug List 2016:
            title: Medicaid Preferred Drug List 2016
            link: /2017/04/05/medicaid-formulary/medicaid-preferred-drug-list-2016/
  CONTACT:
    title: CONTACT
    link: /
    submenu:
      Join Van Lang IPA:
        title: Join Van Lang IPA
        link: /2015/11/07/join-vlipa/
        class: no-menu

mbmenu:
  ABOUT_US:
    title: ABOUT_US
    link: /
    function: loadmenu(0)
    submenu:
      Some_menu:
        title: Menu
        link: /
        havefunction: 1
        function: back(0)
        class: no-menu
      ABOUT_US:
        title: ABOUT_US
        link: /
        class: no-menu
      About_VanLangIPA:
        title: About Van Lang IPA
        link: /2015/11/07/about-us
        class: no-menu
      Out_Leadership:
        title: Out Leadership
        link: /2015/11/07/leadership-team/
        class: no-menu
      Out_Team:
        title: Our Team
        link: /2015/11/07/leadership-team/
        class: no-menu

  FOR PROVIDERS:
    title: FOR PROVIDERS
    link: /
    function: loadmenu(1)
    submenu:
      Some_menu:
        title: Menu
        link: /
        havefunction: 1
        function: back(1)
        class: no-menu
      FOR PROVIDERS:
        title: FOR PROVIDERS
        link: /
        class: no-menu
      Claims:
        title: Claims
        link: /
        class: submenu
        havemenu: 1
        function: pushul(0)
        submenu:
          Some_menu:
            title: Menu
            link: /
            havefunction: 1
            function: backul(0)
          How_to_create_a_claim_batch_in_eCW_for_VLIPA:
            title: How to create a claim batch in eCW for VLIPA
            link: /2015/11/07/guide/how-to-create-a-claim-batch-in-ecw-for-vlipa/
          How_to_setup_paper_claim_in_Athena:
            title: How to setup paper claim in Athena
            link: /2015/11/07/guide/how-to-set-up-paper-claims-in-athena/
          Setup_VLIPA_as_a_favourite_in_Athena:
            title: Setup VLIPA as a favourite in Athena
            link: /2015/11/07/guide/set-up-van-lang-ipa-as-a-favorite-in-athena/
          How_to_file_claims:
            title: How to file claims
            link: /2015/11/07/guide/tips-on-how-to-file-claims/
      Prior_Authorization:
        title: Prior Authorization
        link: /
        class: submenu
        havemenu: 1
        function: pushul(1)
        submenu:
          Some_menu:
            title: Menu
            link: /
            havefunction: 1
            function: backul(1)
          RioTab_Access_Introduction:
            title: RioTab Access Introduction
            link: /2015/11/14/prior-authorization/riotap-intro/
          Authorization:
            title: Authorization
            link: /2016/05/11/prior-authorization/authorization/
      Forms:
        title: Forms
        link: /
        class: submenu
        function: pushul(2)
        havemenu: 1
        submenu:
          Some_menu:
            title: Menu
            link: /
            havefunction: 1
            function: backul(2)
          Letter_of_Agreement(LOA):
            title: Letter of Agreeement(LOA)
            link: /2015/11/14/forms/loa/
          Credentialing)_Pratitioner_Rights_Notice:
            title: (Credentialing) Pracititioner RIghts Notice
            link: /2015/11/14/forms/cred-practitioner-rights/
          Credentialing)_Texas_Standard_Credentialing:
            title: (Credentialing) Texas Standard Credentialing
            link: /2015/11/14/forms/cred-tx-credentialing/
          Credentialing)_Business_Associate_Agreement:
            title: (Credentialing) Business Associate Agreement
            link: /2015/11/14/forms/baa/
      HCC_Coding:
        title: HCC Coding
        link: /
        class: submenu
        havemenu: 1
        function: pushul(3)
        submenu:
          Some_menu:
            title: Menu
            link: /
            havefunction: 1
            function: backul(3)
          Risk Adjustment Documentation, Coding & Quality Toolbook:
            title: Risk Adjustment Documentation, Coding & Quality Toolbook
            link: /2015/11/14/hcc/risk-adjustment-toolbox/
          ICD-9-CM Medicare Diagnosis Codes (Senior Patient, PCP):
            title: ICD-9-CM Medicare Diagnosis Codes (Senior Patient, PCP)
            link: /2015/11/14/hcc/senior-patient/
          ICD 10 - Internal Medicine:
            title: ICD 10 - Internal Medicine
            link: /2015/11/14/hcc/icd10-internal-medicine/
          Documenting and Coding Chronic Conditions Presentation (Sep-2015):
            title: Documenting and Coding Chronic Conditions Presentation (Sep-2015)
            link: /2015/11/14/hcc/coding-chronic-conditions/
          General Coding Education:
            title: General Coding Education
            link: /2015/11/14/hcc/general-coding-education/
      HEDIS / RAF:
        title: HEDIS / RAF
        link: /
        class: submenu
        havemenu: 1
        function: pushul(4)
        submenu:
          Some_menu:
            title: Menu
            link: /
            havefunction: 1
            function: backul(4)
          HEDIS Score Timeline:
            title: HEDIS Score Timeline
            link : /2015/11/14/hedis/score-timeline/
      Diabetes Management:
        title: Diabetes Management
        link: /
        class: submenu
        havemenu: 1
        function: pushul(5)
        submenu:
          Some_menu:
            title: Menu
            link: /
            havefunction: 1
            function: backul(5)
          IMPORTANT 2017 Coverage Changes for Diabetic Supplies :
            title: IMPORTANT 2017 Coverage Changes for Diabetic Supplies
            link: /2017/01/05/diabetes-management/Coverage-for-diabetes-supply/
      Med Management:
        title: Med Management
        link: /
        class: submenu
        havemenu: 1
        function: pushul(6)
        submenu:
          Some_menu:
            title: Menu
            link: /
            havefunction: 1
            function: backul(6)
          Amerigroup Drug Alternatives:
            title: Amerigroup Drug Alternatives
            link: /2016/01/25/med-management/amerigroup-drug-alternatives/
      Video:
        title: Video
        link: /
        class: submenu
        havemenu: 1
        function: pushul(7)
        submenu:
          Some_menu:
            title: Menu
            link: /
            havefunction: 1
            function: backul(7)
          Early detection triples a patient's chances of survival from crc:
            title: Early detection triples a patient's chances of survival from crc
            link: /2015/11/07/video/early-detection-triples-a-patients-chances-of-survival-form-crc/
      TIFL Two-Factor Authentication Guide:
        title: TIFL Two-Factor Authentication Guide
        link: /
        class: no-menu
  PAYER BENEFITS:
    title: PAYER BENEFITS
    link : /
    function: loadmenu(2)
    submenu:
      Some_menu:
        title: Menu
        link: /
        havefunction: 1
        function: back(2)
        class: no-menu
      PAYER BENEFITS:
        title: PAYER BENEFITS
        link : /
        class: no-menu
      Summary of Benefits for Amerivantage Dual Coordination (HMO SNP):
        title: Summary of Benefits for Amerivantage Dual Coordination (HMO SNP)'
        link: /2017/01/05/payer-benefits/2017-benefits-specialty/
        class: no-menu
      Summary of Benefits for Amerivantage Classic (HMO) and Amerivantage Select (HMO):
        title: Summary of Benefits for Amerivantage Classic (HMO) and Amerivantage Select (HMO)
        link: /2016/01/06/payer-benefits/benefits_classic_and_select_2016/
        class: no-menu
  DRUG FORMULARY:
    title: DRUG FORMULARY
    link: /
    function: loadmenu(3)
    submenu:
      Some_menu:
        title: Menu
        link: /
        havefunction: 1
        function: back(3)
        class: no-menu
      DRUG FORMULARY:
        title: DRUG FORMULARY
        link: /
        class: no-menu
      Amerivantage Specialty:
        title: Amerivantage Specialty
        link: /2017/01/05/drug-formulary/2017-amerivantage-specialty-formulary/
        class: no-menu
      Amerivantage Select:
        title: Amerivantage Select
        link: /2017/01/05/drug-formulary/2017-amerivantage-select-formulary/
        class: no-menu
      Amerivantage Classic:
        title: Amerivantage Classic
        link: /2017/01/05/drug-formulary/2017-amerivantage-classic-formulary/
        class: no-menu
      2017 Over-the-Counter Health Products Catalog:
        title: 2017 Over-the-Counter Health Products Catalog
        link: /2017/01/05/drug-formulary/Amerigroup_OTC_Catalog_2017/
        class: no-menu
      Walmart $4 drug list:
        title: Walmart $4 drug list
        link: /2017/04/05/drug-formulary/Walmart_usd4_drug_list/
        class: no-menu
      Medicaid:
        title: Medicaid
        link: /
        class: submenu
        havemenu: 1
        function: pushul(8)
        submenu:
          Some_menu:
            title: Menu
            link: /
            havefunction: 1
            function: backul(8)
          Medicaid Preferred Drug List 2016:
            title: Medicaid Preferred Drug List 2016
            link: /2017/04/05/medicaid-formulary/medicaid-preferred-drug-list-2016/
  CONTACT:
    title: CONTACT
    link: /
    function: loadmenu(4)
    submenu:
      Some_menu:
        title: Menu
        link: /
        havefunction: 1
        function: back(4)
        class: no-menu
      CONTACT:
        title: CONTACT
        link: /Q
        class: no-menu
      Join Van Lang IPA:
        title: Join Van Lang IPA
        link: /2015/11/07/join-vlipa/
        class: no-menu




#TEST YAML
tests:
  title:
    - hello
    - xin chao
    - good night
